// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  endpoint: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  p256Dh: __t.string().name("p_256_dh"),
  auth: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
