// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Expense = __t.object("Expense", {
  id: __t.string(),
  tripId: __t.string(),
  payerId: __t.string(),
  amount: __t.f64(),
  description: __t.string(),
  timestamp: __t.timestamp(),
});
export type Expense = __Infer<typeof Expense>;

export const ExpenseSplit = __t.object("ExpenseSplit", {
  expenseId: __t.string(),
  debtorId: __t.string(),
  amountOwed: __t.f64(),
});
export type ExpenseSplit = __Infer<typeof ExpenseSplit>;

export const Trip = __t.object("Trip", {
  id: __t.string(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Trip = __Infer<typeof Trip>;

export const TripMember = __t.object("TripMember", {
  tripId: __t.string(),
  userId: __t.string(),
});
export type TripMember = __Infer<typeof TripMember>;

export const User = __t.object("User", {
  id: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

